### ISSUE TITLE
"help wanted" "bug" KeyError: "['Symbol' 'AssetType' 'Name' 'Exchange' 'Currency' 'Country' 'Sector'\n 'Industry'] not in index"

### ISSUE THREAD

**Issue by PhilEats** [MCoffey1129/Utilising-Machine-Learning-for-portfolio-selection-with-the-aim-of-out-performing-benchmark-indices#1]
From these lines of code:

 ```
Overview_df = pd.DataFrame()
columns = ['Symbol', 'AssetType', 'Name', 'Exchange', 'Currency', 'Country', 'Sector', 'Industry']

for stock in upd_stock_list:
    time.sleep(0.75)
    base_url = 'https://www.alphavantage.co/query?'
    params = {'function': 'OVERVIEW',
              'symbol': stock,
              'apikey': API_key}

    response = requests.get(base_url, params=params)

    output = response.json()
    if output == {} or list(output.keys())[0] == 'Error Message':
        Temp_data_df = pd.DataFrame()
    else:
        Temp_data_df = pd.DataFrame(list(output.values())).transpose()
        Temp_data_df.columns = [list(output.keys())]
        Temp_data_df = Temp_data_df[columns]

    Overview_df = Overview_df.append(Temp_data_df, ignore_index=True)`
```

I get this error: 

[NDR: directories are edited and shortened to make it easier to read] 

Traceback (most recent call last):
  File "C:\....\Input code.py", line 152, in <module>
    Temp_data_df = Temp_data_df[columns]
  File "C:\....Python39\site-packages\pandas\core\frame.py", line 3030, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\....\Python39\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    indexer, keyarr = ax._convert_listlike_indexer(key)
  **File "C:\....\Python39\site-packages\pandas\core\indexes\multi.py", line 2568, in _convert_listlike_indexer
    raise KeyError(f"{keyarr[mask]} not in index")**
**KeyError: "['Symbol' 'AssetType' 'Name' 'Exchange' 'Currency' 'Country' 'Sector'\n 'Industry'] not in index"**

Tried to convert list into slices, and tried regex , df multi index also, but I'm a newbie in coding, maybe I'm getting it all wrong.. as suggested in updated readme, left only NAME, SECTOR, INDUSTRY in columns tags, but didn't work. @MCoffey1129 can you help with this? Really like your model, this is great and well developed work...

**Comment by MCoffey1129** [comment]
Hi @PhilEats thanks for the question.

1. The "input code" section of this project is simply code used to pull in the data I used from Alpha Vantage. The output of this code has been saved on GITHUB if you want to copy these down on to your computer and start running the "main_assignment" code. The data imported in the "input_code" is  Overview_df (Company overview), BS_data (balance sheet data), CF_data (cashflow data), eps_data (earnings per share data), inc_st_data (income statement data) and monthly_prices (adjusted close price of each stock on the last trading day of each month.

2. With regard to your error I am not 100% certain of the error but it should be relatively easy to solve given that we know what information you should get from Alpha Vantage (Overview_df csv saved on GITHUB). 

Let's break the piece of code down such that we are only looking at one company and go from there. 
(i) In order to run this section of the code you need  to pay for an API key from Alpha Vantage it costs $50 a month ( https://www.alphavantage.co/premium/). The free API key unfortunately only entitles you to 500 API calls a day which is not enough for what we require. As I said all the data is on GITHUB if you do not want to pay for this

(ii) Assuming you have paid for the API key and you are still getting the error let's see if you get the error when trying to run the code for one company Agilent Technologies which has a stock symbol of A. Can you run the following code and let me know the results (the print statements)? Please note this should line up with the Overview_df csv.

  base_url = 'https://www.alphavantage.co/query?'
  params = {'function': 'OVERVIEW',
              'symbol': 'A',
              'apikey': 'insert your API key here'}

  response = requests.get(base_url, params=params)

  output = response.json()
  Temp_data_df = pd.DataFrame(list(output.values())).transpose()
  Temp_data_df.columns = [list(output.keys())]
   Temp_data_df = Temp_data_df[columns]

  print(output)
  print(Temp_data_df)
